Update user_input.html
FOSS-Cell-GECPKD/pixelvibe pull request #190
Opened 2021-05-15 18:30 UTC by CMELAKKIA

## Related Issue 

- #127 

Closes: #127 
### Describe the changes you've made

Enhanced the website view with the modification of index.html, app.js, style.css

## Type of change

Added skin colors for the website

Example how to mark a checkbox:-
- [x] My code follows the code style of this project.
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
NA

## Checklist:
- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

2021-05-15 18:31 UTC, CMELAKKIA commented
@ankitapuri It is working completely fine now. I have migrated the same work in flask application.

2021-05-15 19:03 UTC, ankitapuri commented
@CMELAKKIA  please add a working video related to it , it makes easier to review

2021-05-16 03:46 UTC, arpit456jain requested changes

2021-05-16 03:46 UTC, arpit456jain commented on template/user_input.html
> +    <form id="size-picker" class="size-picker-form scale-up-center" action="/" method="post">
@CMELAKKIA please don't change action="/paint" to "/" it will give error. Leave it as it is before please
rest all is working fine its too good :)

2021-05-16 08:37 UTC, CMELAKKIA commented
> @CMELAKKIA please add a working video related to it , it makes easier to review

It is same as pictures in previous PR.

2021-05-16 08:41 UTC, CMELAKKIA commented
@arpit456jain action have been changed.

2021-05-16 08:42 UTC, CMELAKKIA commented
> @CMELAKKIA please add a working video related to it , it makes easier to review

Could you please refer to the pictures in #190

2021-05-16 08:44 UTC, CMELAKKIA commented
> @CMELAKKIA please add a working video related to it , it makes easier to review

Could you please refer to the pictures in #139

2021-05-16 11:06 UTC, ankitapuri commented
> > @CMELAKKIA please add a working video related to it , it makes easier to review
> 
> After clicking "submit", the next page works completely fine !!
> 
> Could you please refer to the pictures in #139

okay !

2021-05-16 14:21 UTC, adarshvulli approved these changes

2021-05-16 15:08 UTC, merged