Added welcome bot
FOSS-Cell-GECPKD/pixelvibe pull request #69
Opened 2021-03-17 13:35 UTC by itsIapetus

## Related Issue 

- Info about the related issue 

Closes: #45 

Added a welcome bot

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code

## Additional Info (optional)
Any additional information you want to give

## Checklist:

- [ ] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.

2021-03-17 17:51 UTC, adarshvulli approved these changes
good to go

2021-03-17 18:29 UTC, avinal commented on .github/config.yml
> +  Hello there!👋 Welcome to the project!🚀⚡
```suggestion
  Hello there!👋 Welcome to the Pixelvibe project!🚀⚡
```
A particular name looks much nice and presentable.

2021-03-17 18:30 UTC, avinal commented on .github/config.yml
> +  Hello there!👋 Welcome to the project!💖
```suggestion
  Hello there!👋 Welcome to the Pixelvibe project!💖
```

2021-03-17 18:30 UTC, avinal commented on .github/config.yml
> +  Congrats🎉 on getting your first pull request merged! All the best for your amazing open source journey ahead 🚀.
```suggestion
  Congrats🎉 on getting your first pull request merged! All the best for your amazing open-source journey ahead 🚀.
  
```
Add a blank line at the end of the file.

2021-03-17 18:31 UTC, avinal requested changes
Please do the changes

2021-03-17 18:33 UTC, avinal commented
@ankitapuri, please add the app to this repository, we might see it working before merging. https://github.com/behaviorbot/welcome#usage

2021-03-18 09:11 UTC, itsIapetus commented
> @ankitapuri, please add the app to this repository, we might see it working before merging. https://github.com/behaviorbot/welcome#usage

I have added it.

2021-03-18 14:17 UTC, adarshvulli approved these changes

2021-03-18 14:25 UTC, avinal approved these changes

2021-03-18 15:40 UTC, merged