Added canvas and landing popup asking for dimensions
FOSS-Cell-GECPKD/pixelvibe pull request #79
Opened 2021-03-19 12:37 UTC by AtharvaKamble

## Related Issue 

- There was no canvas for drawing 

Closes: #64 

### Describe the changes you've made

I added the drawing section (canvas) and a pop-up as a landing page for dimensions

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Mention any unusual behaviour of your code (Write NA if not)
Any unusual behaviour of your code
NA

## Additional Info (optional)
Any additional information you want to give
NA

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] Any dependent changes have been merged and published in downstream modules.

2021-03-19 16:01 UTC, avinal commented
Hello @AtharvaKamble, thanks for your PR, here are some of the problems you need to fix.
- the `Reset` Button is not working
- Grid size remains the same no matter what size we choose
- There is no option to close the grid

2021-03-19 16:04 UTC, avinal requested changes
Hello @AtharvaKamble, thanks for your PR, here are some of the problems you need to fix.
- the `Reset` Button is not working
- Grid size remains the same no matter what size we choose
- There is no option to close the grid

Rest seems okay, it would be great if you can test it on GitHub Pages too, not required though.

2021-03-19 16:46 UTC, avinal approved these changes

2021-03-19 16:53 UTC, ankitapuri approved these changes

2021-03-19 19:59 UTC, rish-singhal approved these changes

2021-03-20 05:33 UTC, adarshvulli approved these changes

2021-03-20 05:42 UTC, merged