adding home page
FOSS-Cell-GECPKD/pixelvibe pull request #9
Opened 2020-12-28 10:50 UTC by abhiram-anand

2020-12-28 13:46 UTC, BreadGenie requested changes

2020-12-28 13:46 UTC, BreadGenie commented on home.html
> +      <nav class="navbar">
@abhiram-anand the home page design looks nice but it'd be much nicer if the navbar is raised to the top

2020-12-29 09:08 UTC, BreadGenie requested changes

2020-12-29 09:08 UTC, BreadGenie commented on css/home.css
> +  margin: 2% 6% 5% 7%;
idk if it's just on my machine but this is how it looks for me

![Screenshot from 2020-12-29 14-37-17](https://user-images.githubusercontent.com/63963181/103272633-67095200-49e3-11eb-8530-e1707920492c.png)

in my opinion it'd look better if the whole navbar is on top

2020-12-29 09:15 UTC, abhiram-anand commented
I think it's only on yours.
I got something like this


On Tue, Dec 29, 2020, 2:38 PM Bread Genie <notifications@github.com wrote:

> *@BreadGenie* requested changes on this pull request.
> ------------------------------
>
> In css/home.css
> <https://github.com/FOSS-Cell-GECPKD/pixelvibe/pull/9#discussion_r549627110>
> :
>
> > @@ -7,7 +7,7 @@ body {
>    cursor: default;
>  }
>  .navbar {
> -  margin: 4% 6% 5% 7%;
> +  margin: 2% 6% 5% 7%;
>
> idk if it's just on my machine but this is how it looks for me
>
> [image: Screenshot from 2020-12-29 14-37-17]
> <https://user-images.githubusercontent.com/63963181/103272633-67095200-49e3-11eb-8530-e1707920492c.png>
>
> in my opinion it'd look better if the whole navbar is on top
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/FOSS-Cell-GECPKD/pixelvibe/pull/9#pullrequestreview-559440464>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASC4IH3GFY6BTKUXEYMLXJTSXGMCNANCNFSM4VL4E7NA>
> .
>

2020-12-29 09:28 UTC, BreadGenie commented
@abhiram-anand can you provide a screenshot?
also @ankitapuri take a look at this PR

2020-12-29 11:04 UTC, ankitapuri commented
> @abhiram-anand can you provide a screenshot?
> also @ankitapuri take a look at this PR

Yeah I have seen it.  I also suggest that the navbar should be above . It's coming inline with the project description.

2020-12-30 08:11 UTC, abhiram-anand commented
@BreadGenie  here's the screenshot
![Screenshot_2020-12-27_PixelVibe](https://user-images.githubusercontent.com/75875359/103338533-b3689680-4aa4-11eb-9b9f-c3e6df6dc470.png)

2020-12-30 16:40 UTC, Harshit850 commented
I had a new design idea for this landing page, i would like to show you, can i?

2020-12-30 16:44 UTC, ankitapuri commented
> I had a new design idea for this landing page, i would like to show you, can i?

let's discuss in gitter

2021-05-15 19:04 UTC, closed without merging